# Generated by Django 5.1.5 on 2025-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='end_reading',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_reading',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FANTASY', 'Фэнтези'), ('SCIFI', 'Научная фантастика'), ('DETECTIVE', 'Детектив'), ('ROMANCE', 'Романтика'), ('HORROR', 'Ужасы'), ('THRILLER', 'Триллер'), ('HISTORICAL', 'Исторический роман'), ('BIOGRAPHY', 'Биография'), ('ADVENTURE', 'Приключения'), ('MYSTERY', 'Мистика'), ('DRAMA', 'Драма'), ('POETRY', 'Поэзия'), ('PHILOSOPHY', 'Философия'), ('SCIENCE', 'Наука'), ('SELFHELP', 'Саморазвитие'), ('BUSINESS', 'Бизнес-литература'), ('COMICS', 'Комиксы и графические романы'), ('CHILDREN', 'Детская литература'), ('YOUNGADULT', 'Подростковая литература'), ('CLASSIC', 'Классика'), ('RELIGION', 'Религиозная литература'), ('PSYCHOLOGY', 'Психология'), ('COOKING', 'Кулинария'), ('TRAVEL', 'Путешествия'), ('FANTASTICREALISM', 'Фантастический реализм'), ('CYBERPUNK', 'Киберпанк'), ('DYSTOPIA', 'Антиутопия'), ('MAGICREALISM', 'Магический реализм')], max_length=20),
        ),
    ]
