# Generated by Django 5.1.5 on 2025-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_reading',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_reading',
            field=models.DateField(blank=True, null=True),
        ),
    ]
