# Generated by Django 5.1.5 on 2025-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_book_end_reading_alter_book_start_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/'),
        ),
    ]
