# Generated by Django 5.1.5 on 2025-02-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_book_cover_url_book_cover_image_book_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='cover_url',
        ),
    ]
